### ISSUE TITLE
use swagger-ui fork

### ISSUE THREAD

**Issue by pbaille** [metosin/ring-swagger-ui#9]
Hello,

I would be interested in using this fork of swagger-ui: https://github.com/jensoleg/swagger-ui
How can i do this?

Thank you

**Comment by Deraen** [comment]
By making your own fork of this repository and creating your own package with out groupid. You can switch the swagger-ui submodule in this repo to point to the fork instead of upstream version.

[New swagger-ui version update procedure](https://github.com/metosin/ring-swagger-ui#new-swagger-ui-version] on readme should give some idea on how to modify local index.html according to version in swagger-ui.
